services:
  nodejs-monorepo-postgres:
    container_name: nodejs-monorepo-postgres
    image: postgres:17.5-alpine3.22
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - nodejs-monorepo-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
    env_file: apps/backend/.env.prod
    networks:
      - nodejs-monorepo-network
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    hostname: nodejs-monorepo-postgres

  nodejs-monorepo-redis:
    container_name: nodejs-monorepo-redis
    image: redis:8.0.2-alpine
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - nodejs-monorepo-redis-data:/data
    environment:
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DATABASES: ${REDIS_DATABASES}
    env_file: apps/backend/.env.prod
    networks:
      - nodejs-monorepo-network
    healthcheck:
      test: redis-cli -a $REDIS_PASSWORD ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    hostname: nodejs-monorepo-redis

  nodejs-monorepo:
    container_name: nodejs-monorepo
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      nodejs-monorepo-postgres:
        condition: service_healthy
      nodejs-monorepo-redis:
        condition: service_healthy
    env_file: apps/backend/.env.prod
    networks:
      - nodejs-monorepo-network
    hostname: nodejs-monorepo

volumes:
  nodejs-monorepo-postgres-data:
    name: nodejs-monorepo-postgres-data
    driver: local
  nodejs-monorepo-redis-data:
    name: nodejs-monorepo-redis-data
    driver: local

networks:
  nodejs-monorepo-network:
    name: nodejs-monorepo-network
    driver: bridge
    attachable: true
